load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "gui",
    srcs = ["renderer.go"],
    importpath = "github.com/gerzin/chippotto/chippotto/gui",
    visibility = ["//visibility:public"],
)
